### PR TITLE
Adding Coin check balance and claim functionality to CLI

### PR DESCRIPTION
**Pull request by localhuman**
This PR adds the following features to the CLI:
- ability to list unavailable and unclaimed ANC. 
- ability to claim unclaimed ANC

screen shot 2017-07-03 at 7 26 25 pm
screen shot 2017-07-03 at 7 29 00 pm

### CODE REVIEW

**Comment by erikzhang** [comment]
@localhuman can you change the name of the commands to the same style as any other command: verb + noun + argument list
Example:
show gas
claim gas

**Comment by localhuman** [comment]
Thanks for the feedback!  Changes made-

**Review by erikzhang — CHANGES_REQUESTED** [review]
In L370 of MainService.cs, "return false" means to terminate the program. I think it should print some message and return true. Or just "return base.OnCommand(args);"

**Comment by localhuman** [comment]
4d7f73db99a00bb251d5fa03ee9c0887f8f87d87 should resolve this issue

**Review by erikzhang — COMMENTED** [review]
One more thing, what does the return value mean in L45?

**Comment by localhuman** [comment]
That is a good question!  I believe it should be indicating the success of a coin claim, but it is not currently implemented exactly that way.  

Also, in `MainService.cs` L367, the result of the `Claim()` call is not using the return value of the method signature.

Do you think it would make more sense to return `void` instead?

**Comment by erikzhang** [comment]
I think it's best to implement as indicating the success of a coin claim. Otherwise, it should return void.

**Comment by localhuman** [comment]
`Coins.Claim()` now returns a `ClaimTransaction` rather than `bool`. This way it can be called by other methods that may possibly need the resulting transaction of the `Coins.Claim()` method call.  If the call is unsuccessful it returns `null`.

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
