### PR TITLE
Update GUI for a consistent and professional look

### PR DESCRIPTION
**Pull request by ghost**
- Added official NEO icon to all forms
- Added label to ClaimForm to advise users that minimum claim is 1 GAS

### CODE REVIEW

**Comment by erikzhang** [comment]
You changed a lot, more then the icons... and it's hard to review.

**Comment by ghost** [comment]
No I didn't. The changes are because Visual studio converts the icon to a base64 encoded string and embeds it into the .resx files. Surely you must know that? Look at the existing icon in MainForm.resx and toy will see this is the case @erikzhang

**Comment by erikzhang** [comment]
I mean, once you change the .resx files, the code will be regenerated with different order, which makes it hard to review.

**Comment by erikzhang** [comment]
image

**Comment by ghost** [comment]
I appreciate it is hard to review but unfortunately that is outside of my control when using Visual Studio 2017. I did not manually alter the .resx file, Visual Studio did.  I was just trying to help but maybe you (or one of your team) could do it so you are satisfied there is nothing suspicious about it.

At a minimum it would be good if you put a note on the claimform to let people know they can only claim GAS when it is more than 1.  I see a lot of reddit posts about this and it would save the confusion.

Next time you could be a bit more pleasant when responding to people that are trying to help the project @erikzhang.

**Comment by erikzhang** [comment]
Thanks for your suggestions :)

**Pull request closed without merging**
