### PR TITLE
GUI Fixes in Deploy Contract Dialog

### PR DESCRIPTION
**Pull request by belane**
### BEFORE
image
### AFTER
image

### CODE REVIEW

**Comment by jonatanblockchain** [comment]
What about?
2018_02_27_14_30_27_host_de_experiencia_del_shell_de_windows

**Comment by erikzhang** [comment]
@jonatanblockchain That's good.

**Comment by jonatanblockchain** [comment]
@belane also, check out when click Advaned button on Transfer (not sure if its my screen-resolution) I can't "see" the OK/Cancel
neogui-advanced

**Comment by belane** [comment]
I think both things are fixed now

image

image

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
